### ISSUE TITLE
チートの対策をする

### ISSUE THREAD

**Issue by kmurayama-aim** [kmurayama-aim/senka-hal-tokyo#21]
#20 の続き

# 背景
アイテムを移動させるチートがあるので止めたい

# 内容
サーバーで不正な移動を監視する

# 実装方法
#### 現状、通常のアイテムは動かず、レアアイテムはワールド座標に対してx軸方向の移動しかしないことを利用する 
１．アイテムを獲得時にサーバーにアイテムの位置を送る
２．サーバーで記録しているアイテムの初期位置と獲得位置の y、z 座標を確認し、異なっている場合チート
３．チートの場合スコアを増やさず、他のクライアントから該当のアイテムを削除しない
（チートしたプレイヤーの画面からはアイテムが消える）

**Comment by vividmuimui** [comment]
> アイテムを獲得時にサーバーにアイテムの位置を送る

ここで送る位置も偽装(チート)されたらどうなりますか・・？(このissueではその可能性は無視してしまうのもありだとは思います)

**Comment by kmurayama-aim** [comment]
本当ですね、全く考えていなかったです
少し考えてみます！

**Comment by kmurayama-aim** [comment]
練習として始めに書いた実装をやった後、チート対応は一旦打ち切ります！
（理想としては当たり判定をサーバーで持つ必要があるようなので…）
