### ISSUE TITLE
Slack通知をできるようにする

### ISSUE THREAD

**Issue by kmurayama-aim** [kmurayama-aim/senka-hal-tokyo#4]
Slackに通知する

**Comment by vividmuimui** [comment]
slack通知を試すとき、会社のslackのチームにいきなりやるより、個人のslackチームを作ってそっちで試すと色々自由にできて良いと思います。
なにかミスったとしても影響範囲がとても小さいので。

**Comment by kmurayama-aim** [comment]
まずはそのようにやってみます。
ありがとうございます！

**Comment by kmurayama-aim** [comment]
通知テスト

できてるね！
コメントの更新は受け取らないみたい
